### ISSUE TITLE
Readme : fonctions getData et getSensors

### ISSUE THREAD

**Issue by oliviabrd** [LE2P/pySolarDB#3]
@axhenax Lorsque l'on teste les exemples dans "Raw data recovery" du readme, il y a une erreur car dans les fonctions getData et getSensors, l'argument "types" doit être modifié par "sensor_types"

**Comment by axhenax** [comment]
Bonjour
Merci pour le retour, une nouvelle version du README est disponible en tenant compte des corrections à apporter. Une nouvelle version du paquet devrait par ailleurs être publiée dans les jours à venir.
